### ISSUE TITLE
RSS feed URL

### ISSUE THREAD

**Issue by lnmx** [rust-community/blog.community.rs#6]
The RSS feed URL points to `blog.rust-lang.org/feed.xml`, should be `blog.community.rs/feed.xml`, as observed in http://blog.community.rs/2017/04/03/welcome.html --

`<link rel="alternate" type="application/rss+xml" title="The Rust Programming Language Blog" href="http://blog.rust-lang.org/feed.xml" />`

**Comment by skade** [comment]
Thanks!
